// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: network.proto

#include "network.pb.h"
#include "network.grpc.pb.h"

#include <functional>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/channel_interface.h>
#include <grpcpp/impl/client_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/rpc_service_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/sync_stream.h>
namespace network {

static const char* NetworkService_method_names[] = {
  "/network.NetworkService/NetworkData",
};

std::unique_ptr< NetworkService::Stub> NetworkService::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< NetworkService::Stub> stub(new NetworkService::Stub(channel, options));
  return stub;
}

NetworkService::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_NetworkData_(NetworkService_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::BIDI_STREAMING, channel)
  {}

::grpc::ClientReaderWriter< ::network::Data, ::network::Data>* NetworkService::Stub::NetworkDataRaw(::grpc::ClientContext* context) {
  return ::grpc::internal::ClientReaderWriterFactory< ::network::Data, ::network::Data>::Create(channel_.get(), rpcmethod_NetworkData_, context);
}

void NetworkService::Stub::async::NetworkData(::grpc::ClientContext* context, ::grpc::ClientBidiReactor< ::network::Data,::network::Data>* reactor) {
  ::grpc::internal::ClientCallbackReaderWriterFactory< ::network::Data,::network::Data>::Create(stub_->channel_.get(), stub_->rpcmethod_NetworkData_, context, reactor);
}

::grpc::ClientAsyncReaderWriter< ::network::Data, ::network::Data>* NetworkService::Stub::AsyncNetworkDataRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) {
  return ::grpc::internal::ClientAsyncReaderWriterFactory< ::network::Data, ::network::Data>::Create(channel_.get(), cq, rpcmethod_NetworkData_, context, true, tag);
}

::grpc::ClientAsyncReaderWriter< ::network::Data, ::network::Data>* NetworkService::Stub::PrepareAsyncNetworkDataRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncReaderWriterFactory< ::network::Data, ::network::Data>::Create(channel_.get(), cq, rpcmethod_NetworkData_, context, false, nullptr);
}

NetworkService::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      NetworkService_method_names[0],
      ::grpc::internal::RpcMethod::BIDI_STREAMING,
      new ::grpc::internal::BidiStreamingHandler< NetworkService::Service, ::network::Data, ::network::Data>(
          [](NetworkService::Service* service,
             ::grpc::ServerContext* ctx,
             ::grpc::ServerReaderWriter<::network::Data,
             ::network::Data>* stream) {
               return service->NetworkData(ctx, stream);
             }, this)));
}

NetworkService::Service::~Service() {
}

::grpc::Status NetworkService::Service::NetworkData(::grpc::ServerContext* context, ::grpc::ServerReaderWriter< ::network::Data, ::network::Data>* stream) {
  (void) context;
  (void) stream;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace network

